### ISSUE TITLE
Failed to compile aria2 git master with libuv git master

### ISSUE THREAD

**Issue by multiSnow** [aria2/aria2#241]
build with clang 3.5.0, on Linux 3.14-1-amd64 Debian 3.14.5-1 (2014-06-05) x86_64 GNU/Linux

```
  CXX      LibuvEventPoll.lo
LibuvEventPoll.cc:133:5: error: no matching function for call to 'uv_timer_start'
    uv_timer_start(timer, timer_callback, timeout, timeout);
    ^~~~~~~~~~~~~~
/usr/include/uv.h:1393:15: note: candidate function not viable: no known conversion from 'void (uv_timer_t *, int)' to 'uv_timer_cb' (aka 'void (*)(uv_timer_t *)') for
      2nd argument
UV_EXTERN int uv_timer_start(uv_timer_t* handle,
              ^
1 error generated.
Makefile:2254: recipe for target 'LibuvEventPoll.lo' failed
make[3]: *** [LibuvEventPoll.lo] Error 1
```

**Comment by moonman** [comment]
This fix no longer works on openwrt. libuv version was updated to 1.4.2 https://github.com/openwrt/packages/blob/master/libs/libuv/Makefile 
minor is 4 which is less than 10 so code falls back to old behavior.

**Comment by tatsuhiro-t** [comment]
workaround is disable libuv in configure.
As far as I know, there is no particular benefit using libuv with aria2 because we only use it as socket event notification.  In this regard, it is far more reliable to just use built-in epoll backend.

**Comment by nmaier** [comment]
Probably a good idea to make this a `-with`-default-off switch

**Comment by moonman** [comment]
@tatsuhiro-t thank you, this worked. I always thought it was a required library so I never tried to disable it. @nmaier has a point.
